function mae = compute_alignment_mae(alignment_ab, indice_a, indice_b)

mae_begin = mean([ ...
    min(abs(alignment_ab.P(alignment_ab.P(:, 1) == indice_a.index_begin, 2) - indice_b.index_begin)), ...
    min(abs(alignment_ab.P(alignment_ab.P(:, 2) == indice_b.index_begin, 1) - indice_a.index_begin)) ...
    ]);
mae_subtask_2 = mean([ ...
    min(abs(alignment_ab.P(alignment_ab.P(:, 1) == indice_a.index_subtask_2, 2) - indice_b.index_subtask_2)), ...
    min(abs(alignment_ab.P(alignment_ab.P(:, 2) == indice_b.index_subtask_2, 1) - indice_a.index_subtask_2)) ...
    ]);
mae_subtask_3 = mean([ ...
    min(abs(alignment_ab.P(alignment_ab.P(:, 1) == indice_a.index_subtask_3, 2) - indice_b.index_subtask_3)), ...
    min(abs(alignment_ab.P(alignment_ab.P(:, 2) == indice_b.index_subtask_3, 1) - indice_a.index_subtask_3)) ...
    ]);
mae_end = mean([ ...
    min(abs(alignment_ab.P(alignment_ab.P(:, 1) == indice_a.index_end, 2) - indice_b.index_end)), ...
    min(abs(alignment_ab.P(alignment_ab.P(:, 2) == indice_b.index_end, 1) - indice_a.index_end)) ...
    ]);

mae = struct( ...
    'begin', mae_begin, ...
    'subtask_2', mae_subtask_2, ...
    'subtask_3', mae_subtask_3, ...
    'end', mae_end ...
    );

